[package]
name = "bufo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "2.0.0"
lazy_static = "1.4.0"
derive_builder = "0.12.0"

[features]
test_exec = []