name: Test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Setup winlibs
      uses: bwoodsend/setup-winlibs-action@v1
      with:
        tag: 13.1.0-16.0.5-11.0.0-msvcrt-r5
        with_clang: true
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: python helper.py test