name: Test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup LLVM and Clang
      run: |
      {
        sudo apt-get install llvm-16 clang-16 llvm-16-dev libclang-16-dev
        export PATH=$PATH:/usr/lib/llvm-16/bin
      }
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: python helper.py test