name: Test

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Clang
      uses: egor-tensin/setup-clang@v1.4
      with:
        version: 16
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose --release
    - name: Run tests
      run: python helper.py test